# Generated by Django 5.2 on 2025-04-16 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_deals', to=settings.AUTH_USER_MODEL, verbose_name='Favorites'),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
